### ISSUE TITLE
ruby-fifo gem 0.1.0 seems to be broken

### ISSUE THREAD

**Issue by sonots** [shurizzle/ruby-fifo#8]
`lib/ruby-fifo/fifo.rb` is not included.

```
wget https://rubygems.org/downloads/ruby-fifo-0.1.0.gem
tar zxvf ruby-fifo-0.1.0.gem
tar zxvf data.tar.gz
x lib/ruby-fifo.rb
```

This line is wrong > https://github.com/shurizzle/ruby-fifo/blob/fd20588f10296c5d44779660232e529db187439e/ruby-fifo.gemspec#L13

```
s.files                 = Dir['lib/*']
```

I usually write as

```
s.files         = `git ls-files`.split("\n")
```

**Comment by MikeSchroll** [comment]
Any movement to accept this pull request and update the gem?

**Comment by voodoologic** [comment]
`Dir.glob('lib/*')` worked for me.
